### PR TITLE
feat(docker): add docker related files

### PR DESCRIPTION
**Pull request by devsargam**
This pr adds:
- `Dockerfile` -> for creating the image
- `docker-compse.yml` -> simplifies the usuage
- `.dockerignore` -> ignores the unnecessary files

### CODE REVIEW

**Comment by devsargam** [comment]
@sbtaylor15 can you have a look?

**Comment by sbtaylor15** [comment]
@devsargam Did you sign up for hacktoberfest.com?  You can get credit for this PR.

**Comment by devsargam** [comment]
@sbtaylor15 yup I did!

**Comment by sbtaylor15** [comment]
@devsargam can you please fix the [linting errors](https://github.com/ortelius/scec-frontend/actions/runs/6436503340/job/17534268152?pr=27) in the docker file.  Everything else looks good

**Comment by sbtaylor15** [comment]
@devsargam looks like the dockerfile still needs work.  You can run the mega-linter locally.  [Install instructions](https://megalinter.io/latest/mega-linter-runner/).  Also, I updated the repo permissions so you shouldn't need the workflow approval anymore.

**Comment by devsargam** [comment]
@sbtaylor15 can you have a final look?

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Pull request merged**
